package com.model;

public interface Headers {

    int ORDER_BY_NONE = 1;
    int ORDER_BY_DESC = 2;
    int ORDER_BY_ASC = 3;

    //CENTRAL_STORAGE
    String TABLE_CENTRAL_STORAGE = "Central_Storage";
    String COLUMN_CENTRAL_STORAGE_ID = "id";
    String COLUMN_CENTRAL_STORAGE_PRODUCT_NAME = "product_name";
    String COLUMN_CENTRAL_STORAGE_CATEGORY = "category";
    String COLUMN_CENTRAL_STORAGE_RATING = "rating";
    String COLUMN_CENTRAL_STORAGE_QUANTITY = "quantity";
    String COLUMN_CENTRAL_STORAGE_BRAND_NAME = "brand_name";
    String COLUMN_CENTRAL_STORAGE_EXPIRATION_DATE = "expiration_date";
    String COLUMN_CENTRAL_STORAGE_DESCRIPTION = "description";
    String COLUMN_CENTRAL_STORAGE_PRICE = "price";
    String COLUMN_CENTRAL_STORAGE_SHELF_NUMBER = "shelf_number";
    int INDEX_CENTRAL_STORAGE_ID = 1;
    int INDEX_CENTRAL_STORAGE_PRODUCT_NAME = 2;
    int INDEX_CENTRAL_STORAGE_CATEGORY = 3;
    int INDEX_CENTRAL_STORAGE_RATING = 4;
    int INDEX_CENTRAL_STORAGE_QUANTITY = 5;
    int INDEX_CENTRAL_STORAGE_BRAND_NAME = 6;
    int INDEX_CENTRAL_STORAGE_EXPIRATION_DATE = 7;
    int INDEX_CENTRAL_STORAGE_DESCRIPTION = 8;
    int INDEX_CENTRAL_STORAGE_PRICE = 9;
    int INDEX_CENTRAL_STORAGE_SHELF_NUMBER = 10;
    //CENTRAL STORAGE QUERIES
    String QUERY_CENTRAL_STORAGE_START = "SELECT * FROM " + TABLE_CENTRAL_STORAGE;

    String INSERT_INTO_CENTRAL_STORAGE = "INSERT INTO " + TABLE_CENTRAL_STORAGE +
            '(' + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME + ", " + COLUMN_CENTRAL_STORAGE_CATEGORY + ", " +
            COLUMN_CENTRAL_STORAGE_RATING + ", " + COLUMN_CENTRAL_STORAGE_QUANTITY + ", " +
            COLUMN_CENTRAL_STORAGE_BRAND_NAME + ", " + COLUMN_CENTRAL_STORAGE_EXPIRATION_DATE + ", " +
            COLUMN_CENTRAL_STORAGE_DESCRIPTION + ", " + COLUMN_CENTRAL_STORAGE_PRICE + ", " +
            COLUMN_CENTRAL_STORAGE_SHELF_NUMBER + ')' + " VALUES " + "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

    String QUERY_PRODUCT_IN_CENTRAL_STORAGE_BY_NAME_AND_BRAND = "SELECT " + COLUMN_CENTRAL_STORAGE_ID +
            " FROM " + TABLE_CENTRAL_STORAGE + " WHERE " + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME + " = ?" +
            " AND " + COLUMN_CENTRAL_STORAGE_BRAND_NAME + " = ?";

    String QUERY_PRODUCT_IN_CENTRAL_STORAGE_SORT = " ORDER BY " + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME +
            " COLLATE NOCASE ";

    String REMOVE_PRODUCT_IN_CENTRAL_STORAGE_BY_NAME_AND_BRAND = "DELETE FROM " +
            TABLE_CENTRAL_STORAGE + " WHERE " + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME + " = ?" + " AND " +
            COLUMN_CENTRAL_STORAGE_BRAND_NAME + " = ?";

    String SEARCH_PRODUCT_IN_CENTRAL_STORAGE_BY_NAME = "SELECT * FROM " + TABLE_CENTRAL_STORAGE +
            " WHERE " + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME + " LIKE ?";

    String UPDATE_QUANTITY_OF_A_PRODUCT_IN_CENTRAL_STORAGE = "UPDATE " + TABLE_CENTRAL_STORAGE +
            " SET " + COLUMN_CENTRAL_STORAGE_QUANTITY + " = ?" + " WHERE " + COLUMN_CENTRAL_STORAGE_PRODUCT_NAME + " = ?"
            + " AND " + COLUMN_CENTRAL_STORAGE_BRAND_NAME + " = ?";


    //STORAGE
    String TABLE_STORAGE = "Storage1";
    String COLUMN_STORAGE_ID = "id";
    String COLUMN_STORAGE_PRODUCT_NAME = "product_name";
    String COLUMN_STORAGE_CATEGORY = "category";
    String COLUMN_STORAGE_RATING = "rating";
    String COLUMN_STORAGE_QUANTITY = "quantity";
    String COLUMN_STORAGE_BRAND_NAME = "brand_name";
    String COLUMN_STORAGE_EXPIRATION_DATE = "expiration_date";
    String COLUMN_STORAGE_DESCRIPTION = "description";
    String COLUMN_STORAGE_PRICE = "price";
    String COLUMN_STORAGE_SHELF_NUMBER = "shelf_number";
    int INDEX_STORAGE_ID = 1;
    int INDEX_STORAGE_PRODUCT_NAME = 2;
    int INDEX_STORAGE_CATEGORY = 3;
    int INDEX_STORAGE_RATING = 4;
    int INDEX_STORAGE_QUANTITY = 5;
    int INDEX_STORAGE_BRAND_NAME = 6;
    int INDEX_STORAGE_EXPIRATION_DATE = 7;
    int INDEX_STORAGE_DESCRIPTION = 8;
    int INDEX_STORAGE_PRICE = 9;
    int INDEX_STORAGE_SHELF_NUMBER = 10;

}
