/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//KALKIDAN TAMENE    ATR/8747/09
//TINBIT MESIFIN     ATR/5596/09

package awkehgiza;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DepartmentManager extends javax.swing.JFrame {
     
    database db = new database();
    String query;
    Statement stmt;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form DepartmentManager
     */
    public DepartmentManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departmentmanagerlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        branchlbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        branchcombobox = new javax.swing.JComboBox<>();
        passwordField = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        departmentmanagerlbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departmentmanagerlbl.setText("   WELCOME");

        namelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelbl.setText("Name");

        passwordlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordlbl.setText("Password");

        branchlbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branchlbl.setText("Branch");

        branchcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "EAST", "WEST", "SOUTH", "NORTH" }));
        branchcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchcomboboxActionPerformed(evt);
            }
        });

        loginbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginbtn.setText("LOGIN");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(departmentmanagerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nametxt)
                            .addComponent(branchcombobox, 0, 190, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departmentmanagerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nametxt)
                    .addComponent(namelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(branchcombobox)
                    .addComponent(branchlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(passwordField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String pass = new String(passwordField.getPassword());
        if(nametxt.getText().equals("")){
        JOptionPane.showMessageDialog(this, "please enter your name");
        }
        else if(pass.equals("")){
        JOptionPane.showMessageDialog(this, "please enter your password");
        }
        else{
        try {
            db.connect();
            
            String query = "select * from departmentmanagerlogin where name='"+nametxt.getText()+"'and branch='"+branchcombobox.getSelectedItem()+"'and password='"+pass+"';";
            rs = db.stmt.executeQuery(query);
            
            int i=0;
            while(rs.next()){
                i++;
            departmentManagerPage dmp = new departmentManagerPage();
                    dmp.setVisible(true);
                    this.setVisible(false);
            }

            

            if (i==0) {
             
                    JOptionPane.showMessageDialog(this, "Incorrect Username or password");
                }
            

            db.disconnect();

        } catch (Exception e) {
            System.out.println(e);
        }
        }
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void branchcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchcomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchcombobox;
    private javax.swing.JLabel branchlbl;
    private javax.swing.JLabel departmentmanagerlbl;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordlbl;
    // End of variables declaration//GEN-END:variables
}
